### ISSUE TITLE
using ENV with docker-compose and Network-Mode

### ISSUE THREAD

**Issue by Bond246** [karrot-dev/fritzinfluxdb#37]
Hello Ricardo,

best men for rewriting the whole project :-)
Just some questions on migrating:

I would like to use docker-compose with ENV-variables to start the container. I think it is the most simple way while i don't net a .ini-file... volumes and so on.
But after starting the container with my specific configuration i get:
```
2022-06-14 08:43:34,943 - INFO: Starting fritzinfluxdb v1.0.0 (2022-06-11)
2022-06-14 08:43:34,943 - ERROR: InfluxDB bucket not defined
```

And 2nd questin.
The old package needed to be run the container in host-mode network. Is it still the same with the new package or is this obsolet?

Thanks
Bond

My docker-compose looks like this:

```
version: '3'

services:
  fritzinfluxdb:
    container_name: fritzinfluxdb
    image: bbricardo/fritzinfluxdb:1.0.0
    restart: unless-stopped
    networks:
      - my-bridge
    environment:
      # FritzBox configuration
      - FRITZBOX_USERNAME=user
      # this var should be defined in an ".env" file
      - FRITZBOX_PASSWORD=xyz

      # InfluxDB configuration
      - INFLUXDB_VERSION=2
      - INFLUXDB_HOSTNAME=InfluxDB
      - INFLUXDB_ORGANISATION=ubuntu-home
      - INFLUXDB_BUCKT=40_tage
      # this var should be defined in an ".env" file
      - INFLUXDB_TOKEN=crazy-token

      # for more config options check fritzinfluxdb-sample.ini

    # enable to write debug information to docker logs
    # command:
    #   - "python"
    #   - "/app/fritzinfluxdb.py"
    #   - "-v"
    
networks:
  my-bridge:
    external: true
    name: my-bridge
```
